name: OSS Manifest Auto Merge Caller

on:
  pull_request:
    types: [labeled]
    branches:
      - develop
      - 'support/*.*.*'
      - 'support/*.*.*.*'
  issues:
    types: [labeled]

jobs:
  call_oss_auto_merge_workflow:
    uses: rdk-e/build_tools_workflows/.github/workflows/bhc_auto_merge_oss_manifest_pr.yml@develop
    secrets:
      rdke_github_token: ${{ secrets.RDKE_GITHUB_TOKEN }}
