name: "CLA"

permissions:
  contents: read
  pull-requests: write
  actions: write
  statuses: write

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLA-Lite:
    name: "Signature / Check"
    runs-on: ubuntu-latest
    steps:
      - if: (startsWith(github.event.comment.body, 'recheck') || startsWith(github.event.comment.body, 'I have read the CLA Document and I hereby sign the CLA')) || github.event_name == 'pull_request_target'
        uses: rdkcentral/contributor-assistant_github-action@v2.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT }}
        with:
          remote-organization-name: 'rdkcentral'
          remote-repository-name: 'cla_signatures'
          path-to-signatures: 'signatures.json'
          path-to-document: 'https://gist.github.com/rdkcmf-jenkins/c797df2d0f276bbae7c2b394e895c263'
          branch: 'main'
          allowlist: dependabot*, dependabot[bot], dependabot, semantic-release-bot, rdkcm-rdke, rdkcm-bot, copilot, Copilot, github-copilot[bot], github-copilot, copilot[bot], copilot-swe-agent[bot], vbabypublic
          domain-allow-list-file: 'domains.json'
          use-dco-flag: false
          lock-pullrequest-aftermerge: true
          suggest-recheck: true
